#
# NekoProxy Controller Installer for Windows
#
# Installs nekoproxy-controller.exe as a Windows service that starts
# automatically when the server boots (instead of running in a shell window).
#
# Run as Administrator. The service uses nekoproxy-controller.exe from the same
# folder as this script; its database, TLS cert, uploads and .env all live in
# that same folder.
#
# Usage:
#   .\install-controller.ps1                    # register + auto-start on boot
#   .\install-controller.ps1 -StartService      # also start it now
#   .\install-controller.ps1 -DelayedStart      # boot start, delayed (after network)
#   .\install-controller.ps1 -Uninstall         # stop + remove the service
#
# Optional config (writes .env next to the exe if it does not exist):
#   .\install-controller.ps1 -ListenHost 0.0.0.0 -Port 8001 -StartService
#
param(
    [switch]$StartService,
    [switch]$DelayedStart,
    [switch]$Uninstall,
    [switch]$NonInteractive,
    [string]$ListenHost,
    [string]$Port,
    [string]$DatabaseUrl
)

$BinaryName  = "nekoproxy-controller.exe"
$ServiceName = "nekoproxy-controller"

# --- Locate the exe (script dir, then current dir) ---
$ScriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Parent $MyInvocation.MyCommand.Path }
$ExePath = Join-Path $ScriptDir $BinaryName
if (-not (Test-Path $ExePath)) { $ExePath = Join-Path (Get-Location) $BinaryName }
if (-not (Test-Path $ExePath)) {
    Write-Host "ERROR: $BinaryName not found in script directory or current directory." -ForegroundColor Red
    Write-Host "  Script dir : $ScriptDir" -ForegroundColor Yellow
    Write-Host "  Current dir: $(Get-Location)" -ForegroundColor Yellow
    exit 1
}
$ExeDir = Split-Path $ExePath -Parent

# --- Require elevation ---
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "ERROR: Run PowerShell as Administrator to install or remove the service." -ForegroundColor Red
    exit 1
}

# --- Uninstall path ---
if ($Uninstall) {
    Write-Host ""
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host "  Uninstall NekoProxy Controller (Windows service)" -ForegroundColor Cyan
    Write-Host "================================================" -ForegroundColor Cyan
    Write-Host ""
    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc) {
        if ($svc.Status -ne "Stopped") {
            Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 2
        }
        Push-Location $ExeDir
        try { & $ExePath remove } finally { Pop-Location }
        Write-Host "[OK] Service removed. Database and .env were left in place." -ForegroundColor Green
    } else {
        Write-Host "[!] Service not installed." -ForegroundColor Yellow
    }
    Write-Host ""
    exit 0
}

Write-Host ""
Write-Host "================================================" -ForegroundColor Cyan
Write-Host "  Install NekoProxy Controller (Windows service)" -ForegroundColor Cyan
Write-Host "================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Exe   : $ExePath" -ForegroundColor Gray

# --- Optional .env next to the exe ---
$configPath = Join-Path $ExeDir ".env"
if (Test-Path $configPath) {
    Write-Host "Config: $configPath (existing - left untouched)" -ForegroundColor Gray
} elseif ($ListenHost -or $Port -or $DatabaseUrl -or (-not $NonInteractive -and
        (Read-Host "Write a .env now? Controller works with defaults (0.0.0.0:8001). [y/N]") -match '^(y|yes)$')) {
    if (-not $ListenHost -and -not $NonInteractive) { $ListenHost = Read-Host "Listen address [0.0.0.0]" }
    if (-not $Port -and -not $NonInteractive)       { $Port       = Read-Host "Listen port [8001]" }
    if (-not $DatabaseUrl -and -not $NonInteractive){ $DatabaseUrl = Read-Host "Database URL [sqlite:///./nekoproxy.db]" }
    if (-not $ListenHost)  { $ListenHost  = "0.0.0.0" }
    if (-not $Port)        { $Port        = "8001" }
    if (-not $DatabaseUrl) { $DatabaseUrl = "sqlite:///./nekoproxy.db" }
    $lines = @(
        "# NekoProxy Controller configuration - generated by install-controller.ps1 on $(Get-Date -Format s)",
        "NEKO_HOST=$ListenHost",
        "NEKO_PORT=$Port",
        "NEKO_DATABASE_URL=$DatabaseUrl"
    )
    # ASCII (no BOM) - a UTF-8 BOM would make the loader miss the first key.
    Set-Content -Path $configPath -Value $lines -Encoding ascii
    Write-Host "Config: $configPath (created)" -ForegroundColor Green
} else {
    Write-Host "Config: using defaults (0.0.0.0:8001, sqlite:///./nekoproxy.db next to the exe)" -ForegroundColor Gray
}
Write-Host ""

# --- Already installed? ---
$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "[!] Service already installed. Use -Uninstall first to reinstall." -ForegroundColor Yellow
    exit 1
}

# --- Register (run from exe dir so the SCM ImagePath is correct) ---
Push-Location $ExeDir
try {
    & $ExePath install
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: Service registration failed (exit code $LASTEXITCODE)." -ForegroundColor Red
        exit 1
    }
    Write-Host "[OK] Service registered." -ForegroundColor Green

    # --- Start on boot ---
    if ($DelayedStart) {
        & sc.exe config $ServiceName start= delayed-auto | Out-Null
        Write-Host "[OK] Startup type: Automatic (Delayed Start)." -ForegroundColor Green
    } else {
        & sc.exe config $ServiceName start= auto | Out-Null
        Write-Host "[OK] Startup type: Automatic." -ForegroundColor Green
    }

    # --- Crash / exit recovery: let the SCM restart the controller if it dies ---
    & sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/10000/restart/30000 | Out-Null
    & sc.exe failureflag $ServiceName 1 | Out-Null
    Write-Host "[OK] Recovery: auto-restart after 5s / 10s / 30s." -ForegroundColor Green

    if ($StartService) {
        Start-Service -Name $ServiceName
        Start-Sleep -Seconds 4
        $svc = Get-Service -Name $ServiceName
        if ($svc.Status -eq "Running") {
            Write-Host "[OK] Controller started." -ForegroundColor Green
        } else {
            Write-Host "[!] Service status: $($svc.Status). Check logs\$ServiceName.log" -ForegroundColor Yellow
        }
    } else {
        Write-Host ""
        Write-Host "Start now with: Start-Service $ServiceName" -ForegroundColor Cyan
    }
} finally {
    Pop-Location
}

Write-Host ""
Write-Host "The controller will now start automatically every time the server boots." -ForegroundColor Green
Write-Host "Web UI (HTTPS, self-signed on first run): https://<server-ip>:$(if ($Port) { $Port } else { '8001' })" -ForegroundColor Green
Write-Host "If clients are remote, allow the port:" -ForegroundColor Gray
Write-Host "  New-NetFirewallRule -DisplayName 'NekoProxy Controller' -Direction Inbound -Action Allow -Protocol TCP -LocalPort $(if ($Port) { $Port } else { '8001' })" -ForegroundColor Gray
Write-Host ""
Write-Host "Useful commands:" -ForegroundColor Cyan
Write-Host "  Start-Service $ServiceName" -ForegroundColor Gray
Write-Host "  Stop-Service  $ServiceName" -ForegroundColor Gray
Write-Host "  Get-Service   $ServiceName" -ForegroundColor Gray
Write-Host "  Logs : $ExeDir\logs\$ServiceName.log" -ForegroundColor Gray
Write-Host "  Data : $ExeDir\nekoproxy.db  (and *-cert.pem / *-key.pem)" -ForegroundColor Gray
Write-Host "  Remove: .\install-controller.ps1 -Uninstall" -ForegroundColor Gray
Write-Host ""
