#!/bin/bash
#
# NekoProxy Controller Installer
#
# This script installs the NekoProxy controller as a systemd service.
# It will prompt for configuration options and set everything up.
#
# Usage: sudo ./install-controller.sh
#

set -e

# Configuration
INSTALL_DIR="/opt/nekoproxy"
CONFIG_FILE="/etc/nekoproxy/controller.env"
SERVICE_NAME="nekoproxy-controller"
BINARY_NAME="nekoproxy-controller"
DATA_DIR="/var/lib/nekoproxy"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

print_header() {
    echo ""
    echo -e "${CYAN}============================================================${NC}"
    echo -e "${CYAN}$1${NC}"
    echo -e "${CYAN}============================================================${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}! $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

# Detect init system: systemd (Ubuntu/Debian) or OpenRC (Alpine)
use_systemd() {
    command -v systemctl >/dev/null 2>&1 && systemctl list-units --type=service >/dev/null 2>&1
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Detect the script directory and binary
find_binary() {
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    # Look for binary in common locations
    if [[ -f "$SCRIPT_DIR/$BINARY_NAME" ]]; then
        BINARY_PATH="$SCRIPT_DIR/$BINARY_NAME"
    elif [[ -f "./$BINARY_NAME" ]]; then
        BINARY_PATH="$(pwd)/$BINARY_NAME"
    else
        print_error "Cannot find $BINARY_NAME binary"
        echo "Please run this script from the directory containing $BINARY_NAME"
        exit 1
    fi

    print_success "Found binary: $BINARY_PATH"
}

# Prompt for configuration
prompt_config() {
    print_header "NekoProxy Controller Configuration"

    # Listen address
    echo ""
    echo "Enter the IP address to listen on (0.0.0.0 for all interfaces)"
    read -p "Listen IP [0.0.0.0]: " LISTEN_HOST
    LISTEN_HOST="${LISTEN_HOST:-0.0.0.0}"

    # Listen port
    echo ""
    echo "Enter the port to listen on"
    read -p "Listen Port [8001]: " LISTEN_PORT
    LISTEN_PORT="${LISTEN_PORT:-8001}"

    # Agent registration secret
    echo ""
    echo "Set an agent registration secret (recommended)."
    echo "Agents must provide this secret to register. Leave blank to allow any agent to register."
    read -p "Agent secret [leave blank to skip]: " AGENT_SECRET

    # Debug mode
    echo ""
    read -p "Enable debug mode? (y/n) [n]: " DEBUG_MODE
    if [[ "$DEBUG_MODE" == "y" || "$DEBUG_MODE" == "Y" ]]; then
        DEBUG="true"
    else
        DEBUG="false"
    fi

    # Summary
    print_header "Configuration Summary"
    echo "  Listen Address: $LISTEN_HOST:$LISTEN_PORT"
    echo "  Agent Secret:   ${AGENT_SECRET:-(none — any agent can register)}"
    echo "  Debug Mode:     $DEBUG"
    echo "  Database:       $DATA_DIR/nekoproxy.db"
    echo "  TLS:            Auto-generated self-signed cert on first start"
    echo ""

    read -p "Is this correct? (y/n): " CONFIRM
    if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
        echo "Installation cancelled."
        exit 0
    fi
}

# Create directories
create_directories() {
    print_header "Creating directories..."

    mkdir -p "$INSTALL_DIR"
    mkdir -p "$(dirname "$CONFIG_FILE")"
    mkdir -p "$DATA_DIR"

    print_success "Created $INSTALL_DIR"
    print_success "Created $(dirname "$CONFIG_FILE")"
    print_success "Created $DATA_DIR"
}

# Install binary
install_binary() {
    print_header "Installing binary..."

    cp "$BINARY_PATH" "$INSTALL_DIR/$BINARY_NAME"
    chmod +x "$INSTALL_DIR/$BINARY_NAME"

    print_success "Installed $INSTALL_DIR/$BINARY_NAME"
}

# Create configuration file
create_config() {
    print_header "Creating configuration..."

    cat > "$CONFIG_FILE" << EOF
# NekoProxy Controller Configuration
# Generated by install-controller.sh on $(date)

# Server settings
NEKO_HOST=$LISTEN_HOST
NEKO_PORT=$LISTEN_PORT
NEKO_DEBUG=$DEBUG

# Database
NEKO_DATABASE_URL=sqlite:///$DATA_DIR/nekoproxy.db

# Agent settings
NEKO_HEARTBEAT_INTERVAL=30
NEKO_HEARTBEAT_TIMEOUT=90

# Stats cleanup (days)
NEKO_STATS_RETENTION_DAYS=30
EOF

    if [[ -n "$AGENT_SECRET" ]]; then
        echo "" >> "$CONFIG_FILE"
        echo "# Agent registration secret" >> "$CONFIG_FILE"
        echo "NEKO_AGENT_SECRET=$AGENT_SECRET" >> "$CONFIG_FILE"
    fi

    # Secure the config file
    chmod 600 "$CONFIG_FILE"

    print_success "Created $CONFIG_FILE"
}

# Create systemd or OpenRC service (Alpine uses OpenRC)
create_service() {
    if use_systemd; then
        print_header "Creating systemd service..."

        cat > "/etc/systemd/system/$SERVICE_NAME.service" << EOF
[Unit]
Description=NekoProxy Controller
Documentation=https://github.com/your-repo/nekoproxy
After=network.target network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=$DATA_DIR
EnvironmentFile=$CONFIG_FILE
ExecStart=$INSTALL_DIR/$BINARY_NAME
Restart=always
RestartSec=5
StartLimitIntervalSec=60
StartLimitBurst=3

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=$SERVICE_NAME

# Security hardening
NoNewPrivileges=true
ProtectHome=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

        print_success "Created /etc/systemd/system/$SERVICE_NAME.service"
        systemctl daemon-reload
        print_success "Reloaded systemd"
    else
        print_header "Creating OpenRC service (Alpine)..."

        cat > "/etc/init.d/$SERVICE_NAME" << INITD
#!/sbin/openrc-run

description="NekoProxy Controller"
command="/bin/sh"
command_args="-c 'set -a; [ -r $CONFIG_FILE ] && . $CONFIG_FILE; set +a; exec $INSTALL_DIR/nekoproxy-controller'"
command_background="yes"
pidfile="/run/nekoproxy-controller.pid"
output_log="/var/log/nekoproxy-controller.log"
error_log="/var/log/nekoproxy-controller.log"

depend() {
    need net
}
INITD
        chmod +x "/etc/init.d/$SERVICE_NAME"
        print_success "Created /etc/init.d/$SERVICE_NAME"
    fi
}

# Enable and start service
start_service() {
    print_header "Starting service..."

    if use_systemd; then
        systemctl enable "$SERVICE_NAME"
        print_success "Enabled $SERVICE_NAME to start on boot"
        systemctl start "$SERVICE_NAME"
        print_success "Started $SERVICE_NAME"
        sleep 2
        if systemctl is-active --quiet "$SERVICE_NAME"; then
            print_success "Service is running!"
        else
            print_warning "Service may have issues. Check: journalctl -u $SERVICE_NAME -f"
        fi
    else
        rc-update add "$SERVICE_NAME" default 2>/dev/null || true
        print_success "Enabled $SERVICE_NAME to start on boot"
        "/etc/init.d/$SERVICE_NAME" start
        print_success "Started $SERVICE_NAME"
        sleep 2
        if "/etc/init.d/$SERVICE_NAME" status >/dev/null 2>&1; then
            print_success "Service is running!"
        else
            print_warning "Service may have issues. Check: /var/log/nekoproxy-controller.log"
        fi
    fi
}

# Show final instructions
show_instructions() {
    print_header "Installation Complete!"

    echo ""
    echo "The NekoProxy controller has been installed and started."
    echo ""
    echo "Web UI: ${CYAN}https://$LISTEN_HOST:$LISTEN_PORT${NC}"
    echo "API:    ${CYAN}https://$LISTEN_HOST:$LISTEN_PORT/api/v1/${NC}"
    echo ""
    echo "TLS: A self-signed certificate was auto-generated on first start."
    echo "     Check the logs for the certificate SHA-256 fingerprint:"
    if use_systemd; then
        echo "     ${CYAN}journalctl -u $SERVICE_NAME | grep fingerprint${NC}"
    else
        echo "     ${CYAN}grep fingerprint /var/log/nekoproxy-controller.log${NC}"
    fi
    echo "     Share this fingerprint with your agents for verification."
    echo ""
    echo "Useful commands:"
    if use_systemd; then
        echo "  ${CYAN}systemctl status $SERVICE_NAME${NC}    - Check service status"
        echo "  ${CYAN}systemctl restart $SERVICE_NAME${NC}   - Restart the controller"
        echo "  ${CYAN}systemctl stop $SERVICE_NAME${NC}      - Stop the controller"
        echo "  ${CYAN}journalctl -u $SERVICE_NAME -f${NC}    - View live logs"
    else
        echo "  ${CYAN}rc-service $SERVICE_NAME status${NC}   - Check service status"
        echo "  ${CYAN}rc-service $SERVICE_NAME restart${NC}  - Restart the controller"
        echo "  ${CYAN}rc-service $SERVICE_NAME stop${NC}      - Stop the controller"
        echo "  ${CYAN}tail -f /var/log/nekoproxy-controller.log${NC} - View logs"
    fi
    echo ""
    echo "Configuration file: ${CYAN}$CONFIG_FILE${NC}"
    echo "Database location:  ${CYAN}$DATA_DIR/nekoproxy.db${NC}"
    echo "Binary location:    ${CYAN}$INSTALL_DIR/$BINARY_NAME${NC}"
    echo ""
    echo "To reconfigure, edit $CONFIG_FILE and restart the service."
    echo ""
}

# Uninstall function
uninstall() {
    print_header "Uninstalling NekoProxy Controller..."

    if use_systemd; then
        if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
            systemctl stop "$SERVICE_NAME"
            print_success "Stopped service"
        fi
        if systemctl is-enabled --quiet "$SERVICE_NAME" 2>/dev/null; then
            systemctl disable "$SERVICE_NAME"
            print_success "Disabled service"
        fi
        rm -f "/etc/systemd/system/$SERVICE_NAME.service"
        systemctl daemon-reload
    else
        "/etc/init.d/$SERVICE_NAME" stop 2>/dev/null || true
        rc-update del "$SERVICE_NAME" default 2>/dev/null || true
        rm -f "/etc/init.d/$SERVICE_NAME"
        print_success "Stopped and removed OpenRC service"
    fi

    rm -f "$CONFIG_FILE"
    rm -f "$INSTALL_DIR/$BINARY_NAME"

    print_warning "Database preserved at $DATA_DIR/nekoproxy.db"
    print_warning "To remove all data: rm -rf $DATA_DIR"

    print_success "NekoProxy Controller has been uninstalled"
}

# Main
main() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         NekoProxy Controller Installer                    ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"

    # Check for uninstall flag
    if [[ "$1" == "--uninstall" || "$1" == "-u" ]]; then
        check_root
        uninstall
        exit 0
    fi

    # Check for help
    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
        echo ""
        echo "Usage: sudo ./install-controller.sh [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  -h, --help       Show this help message"
        echo "  -u, --uninstall  Uninstall the controller"
        echo ""
        exit 0
    fi

    check_root
    find_binary
    prompt_config
    create_directories
    install_binary
    create_config
    create_service
    start_service
    show_instructions
}

main "$@"
